### ISSUE TITLE
Addon files are not placed under addons/ folder.

### ISSUE THREAD

**Issue by GsLogiMaker** [daleblackwood/goshapes#1]
Installing this addon from the Godot AssetLib places the folders in the project's top directory instead of within its own addon folder.

**Comment by decryptedchaos** [comment]
Confirmed.  although, since this has been opened 2 and a half months with zero acknowledgement i assume nobody cares about fixing it

**Comment by daleblackwood** [comment]
Yep, sorry about that -- I'm unfortunately not often able work on this project. I will fast-track any pull request that attempts to fix the error or endeavour to modify it when I return next month.

**Comment by daleblackwood** [comment]
I've just made some updates that move files under the addon structure, as requested, and made some gdscript changes to fix compilation under the Godot 4 RC. Hopefully this resolves the matter.
