### ISSUE TITLE
Error after installing the addon (Godot 4.2)

### ISSUE THREAD

**Issue by dimixar** [daleblackwood/goshapes#10]
I've got an error after installing this addon in my project.

It says that it cannot call `_init()` function from the parent class.
After a short investigation it seems like it cannot call the `_init()` function from Shaper class which is a base `Resource` class.

It seems like the Resource class doesn't have any builtin `_init()` function. And the errors disappeared after adding an empty `_init()` function in `Shaper` class. So if this doesn't break anything else in the addon, it should be an easy fix.

Screenshot with logs:
<img width="976" alt="image" src="https://github.com/daleblackwood/goshapes/assets/759656/8907dd8e-d57e-4fb3-a3d0-0715b7bb5873">

**Comment by darkhog** [comment]
Can confirm. Shame as it seems like a nice addon that would compliment Cyclops Level Builder for me.

@daleblackwood could you please take a look?
