### ISSUE TITLE
feature request: allow "edge nodes" when using a WallMeshShaper

### ISSUE THREAD

**Issue by GGAlanSmithee** [daleblackwood/goshapes#16]
As the video shows. Allow the user to set an optional `Edge Mesh` option to the `WallMeshShaper` that would be used by the builder to insert there at the position of the first and last point in the path.

I would be willing to give this a shot, as it _should_ be fairly straight forward, if you would be interested in this.

https://github.com/user-attachments/assets/ed93927c-3b8e-4ec0-b820-6d4640436c3b

**Comment by GGAlanSmithee** [comment]
lol, started playing around with this, adding an additional `WallMeshEdgeShaper`/`WallMeshEdgeBuilder` in order to re-use as much code as possible, which makes me realize, it would be somewhat easy to allow for segmented/alternating walls in the `WallMeshShaper`


https://github.com/user-attachments/assets/64a5a310-224a-492e-9719-ab036b98a33a

**Comment by GGAlanSmithee** [comment]
To speak to the original post in this issue, I think creating a new shaper type for this would be overkill, as there would always only be two mesh instances (placed at point 0 and n), and always only under certain conditions, such as there being a `WallMeshShaper`, it having `closed=false`, and `line=0`, so with that said, I think adding an additional `@export` to the `WallMeshShaper` (`edge_shape`) would make sense, imo.

**Comment by GGAlanSmithee** [comment]
turns out, it's not _quite_ as easy as just placing the edge shapes at the position of the first and last point, since the mesh can extend beyond that, so I guess one would need to look up the positions from the `Array[MeshSet]` of the `WallMeshShaper`.

**Comment by GGAlanSmithee** [comment]
This one is stomping me. Would appreciate a pointer @daleblackwood (given that this is something you would be interested in, of course)

**Comment by daleblackwood** [comment]
Great idea and awesome examples! As Goshapes is a hobby project, I don't get a lot of time to add features, though if you create a PR with the above and it gels with the project, I'll happily incorporate it.

**Comment by GGAlanSmithee** [comment]
Alright @daleblackwood I will give it a shot, but will need to up my understanding of the mesh merging functionality, so will probably be a while

**Comment by daleblackwood** [comment]
I've added "gaps" to allow for wall meshes to be broken up, nothing on edges yet, but a strong start. It's on the threading branch: https://github.com/daleblackwood/goshapes/tree/feature/threading

**Comment by GGAlanSmithee** [comment]
@daleblackwood the gaps feature is amazing, this is a great addition, and will complement the edge mesh, if it's added eventually

**Comment by daleblackwood** [comment]
WallMeshSegmentShaper in v1.3.1 has preliminary support for this, let me know how you go.
