### ISSUE TITLE
Feature request: Make it possible to have straight edges when using rounding > 0 (PR)

### ISSUE THREAD

**Issue by GGAlanSmithee** [daleblackwood/goshapes#18]
See the two screenshots. In the first - without rounding - the edge is straight, which I would like to be able to keep straight, even when rounding > 0, which is not the case, as can be seen in the second screenshot.

![image](https://github.com/user-attachments/assets/e321672b-5c5e-455a-845b-8178f2795ae8)
![image](https://github.com/user-attachments/assets/87062216-6162-42a7-b58c-4819c24d4be3)

**Comment by GGAlanSmithee** [comment]
This could easily be implemented in the `round_path_it` function, preferably behind a property setting (not implemented in the screenshot)

![image](https://github.com/user-attachments/assets/f8f591cf-467a-4c9a-a6c9-b525d6936f46)
![image](https://github.com/user-attachments/assets/583fe9e8-bb8c-4635-88cb-d8d3d15c59b4)

**Comment by GGAlanSmithee** [comment]
sent a PR to `v1.2` in #19

**Comment by daleblackwood** [comment]
Fixed in 1.3
