### ISSUE TITLE
Edit by selecting shapes "inherit" the shape

### ISSUE THREAD

**Issue by marcosn41** [daleblackwood/goshapes#2]
I encountered a problem when working with multiple shapes. When I edit a shape and select a second shape to edit, the second shape changes to the same shape as the previous shape I edited.

GoShape - Master repo
Godot - 4 beta 1

**Comment by marcosn41** [comment]
Ok, sorry for that, i dont know make unique not working on my project, make new one and trying and works fine!

**Comment by daleblackwood** [comment]
I've made this the default behaviour in 1.1.2, released just now.
