### ISSUE TITLE
Feature Request: Add a plateau_height setting to the CapMoundShaper 

### ISSUE THREAD

**Issue by GGAlanSmithee** [daleblackwood/goshapes#23]
As shown in the video below, it would be cool to be able to either set a `plateau_height`, or alternatively to add a new shaper; `CapPlateauShaper`, which would allow the user to create mounds-like objects, that has a hard cutoff at a certain height.

The example in the video is not really a solution for this, because it has two issues:

1. it does not simplify the geometry, it simply hard caps the already generated vertecies at `y <= plateau_height`
2. as can be seen in the video, the plateau actually changes the incline of the mound, which is probably not what you want
 
https://github.com/user-attachments/assets/8f9a57d3-fcaf-468d-b757-5806c56b4816

**Comment by daleblackwood** [comment]
Good idea and nice demonstration. I'll consider for 1.4.

**Comment by daleblackwood** [comment]
Now in merged into the 1.4 branch
