### ISSUE TITLE
(v1.2) When using a MultiShaper with a CapMoundShaper + ScatterShaper, "Place on Ground" does not work

### ISSUE THREAD

**Issue by GGAlanSmithee** [daleblackwood/goshapes#24]
Using a `MultiShaper` with a `CapMoundShaper` + a `ScatterShaper` makes a lot of sense if you, for example, want to build an island with trees on it. Unfortunately, the `ScatterShaper` "Place on Ground" option does not seem to work in this case. See the video for an example.

https://github.com/user-attachments/assets/714fe9e2-69ff-4046-9d9f-df4912e2305e

**Comment by GGAlanSmithee** [comment]
there is a chance that this actually _does_ work, but the node is never updated, because the only way I ever found to execture this functionality (place scattered meshes on an underlying shape) is to manually select the node in the scene tree, and this is not possible with a `MultiShaper`, since in that case, the `ScatterShaper` is a nested property, and not directly selectable in the scenegraph.

In other words, I can re-produce this with a separate `ScatterShaper` node, which is _not_ placed correctly, even when hitting `Redraw Selected`. As a matter of fact - hitting `Redraw Selected` makes it _not_ placed on the underlying shape, which indicates that the issue at hand is not directly related to the `MultiShape`.

I will create a separate issue for this, and if I find the underlying issue, submit a PR. Perhaps its because of the order of the shapes being processed.

**Comment by GGAlanSmithee** [comment]
Yes - whether or not the `ScatterShaper`s meshes get's placed on an underlying meshe's surface depends on the order it occurs in the scenetree. Is this something you would care to have fixed @daleblackwood? I think it would be hard to fix all of these cases, but it could be alleviated by processing `ScatterShapers` (and then other shapers with `place_on_ground=true`) last.

**Comment by GGAlanSmithee** [comment]
The raycast that is performed in the `ScatterShaper`s `build` function does not hit the collider of the other shape, when both are in the same `MultiShaper`. I have no idea why this is the case. I tried changing the configuration of the ray, making sure nothing is excluded, etc, but no luck so far, but that is def. the reason why this doesn't work

**Comment by GGAlanSmithee** [comment]
I really can't figure out why this is happening, no matter what I try, I can't get the ray to collide. For now, I will reside to using separate shapes, that share `PathOptions` and `GoCurve`. The only annoyance is that I have to select all affected `Goshape`s and hit "Redraw Selected" for the changes to be applied after I change the curve, for example, but it's totally OK.

**Comment by daleblackwood** [comment]
I've seen similar things happen recently with placement raycasts on 4.2.x, I haven't done a deep dive yet but simple solutions haven't worked for me either.

**Comment by daleblackwood** [comment]
Resolved using build ordering in 1.3.x

**Comment by GGAlanSmithee** [comment]
amazing @daleblackwood 💯
