### ISSUE TITLE
Feature Request: Make it possible to set a max height for ScatterShaper

### ISSUE THREAD

**Issue by GGAlanSmithee** [daleblackwood/goshapes#28]
When investigating the issue raised in #24 I realized that it would be really cool to have a `max_height` (and perhaps a `min_height`) in the `ScatterShaper` to effectively limit what altitudes (y values) items can be scattered. This would allow for thins such as tree-lines on a mountain / hill.

In the screenshot below you can somewhat see what this would look like (with the exception of the presense of the bug described in #24)

![image](https://github.com/user-attachments/assets/4c8a8b25-4f38-489a-82fa-9a7b63f1794e)

**Comment by daleblackwood** [comment]
Slam dunk idea, will do in 1.4 - alternatively, will accept PRs.

**Comment by GGAlanSmithee** [comment]
Thanks! I will do a PR for this @daleblackwood, should be very straight forward

**Comment by daleblackwood** [comment]
Now merged into the v1.4 branch

**Comment by GGAlanSmithee** [comment]
wow, you were too quick :D
