### ISSUE TITLE
Feature Request: Consider raising some of the ranges

### ISSUE THREAD

**Issue by GGAlanSmithee** [daleblackwood/goshapes#29]
Not sure what reasoning there are behind the current limits (such as `40` for the `line` property in `PathOptions` for example) but I would ask you to consider raising (and lowering to allow for negative values where it makes sense) these, if there are no technical reason not to do that. It would simply allow for greater creativity.

**Comment by daleblackwood** [comment]
Absolutely - often the range I arrived with were just useful in my own tests. Feel free to open a PR with your expanded ranges (and maybe a few justifications for the new values) and I'll gladly review - my goal with ranges is to find a balance between easy to use, non-breaking and flexible.

**Comment by daleblackwood** [comment]
I have raised a few ranges in the v1.3 branch in the meantime.

**Comment by daleblackwood** [comment]
Some ranges have been raised, we'll raise others on a case-by-case
