### ISSUE TITLE
Parameters/variables description

### ISSUE THREAD

**Issue by StalfFromValenwood** [daleblackwood/goshapes#3]
You now can add descriptions to variables in Godot, this can be very helpful as a built-in documentation-like feature, because I found all these options and sub-resources confusing at first.

You just need to do that (for example):
`## Set the height of the shape`
`var shape_height := 1.0`

**Comment by daleblackwood** [comment]
Great suggestion, I wasn't aware of that when developing in pre-alpha. I'll fast-track any PR that attempts to add descriptions or add them myself when I make revisions in the next few months.

**Comment by daleblackwood** [comment]
As of release 1.1.2, the commenting on properties should be dramatically increased. At time of writing it's under review in the Godot asset store. It can also be downloaded from the release tab here.
