### ISSUE TITLE
top menu changes order depending on whether a goshape is selected or not

### ISSUE THREAD

**Issue by GGAlanSmithee** [daleblackwood/goshapes#37]
Given the way the menu is constructed in code, the menu options that are conditionally shown, only when a shape is selected, pushes down the menu choices that are always present. This is surprising, and not optimal from a UX perspective. I propose that  you:

1. always keep the "static" menu choices on top, and
2. add a border to create a section between the menu choises

https://github.com/user-attachments/assets/0f15c9a5-192e-488b-a3cb-afea12c9ddf4

**Comment by daleblackwood** [comment]
I'm going to refactor menus for 1.4 - there's some janky control hacking going on that I shouldn't be doing.

**Comment by daleblackwood** [comment]
I've refactored the menus to make it a bit easier to use, let me know if you've got any further feedback.
