### ISSUE TITLE
Adding GoShapes to groups seems to not work

### ISSUE THREAD

**Issue by Gemini04126** [daleblackwood/goshapes#48]
I've attempted to add a GoShapes node to a group (for the sake of different footstep sounds, if you're curious) and it doesn't do the same for the meshes and collision shapes it generates. Is there a way that they could inherit the GoShapes node's group?

**Comment by daleblackwood** [comment]
Sure thing - can you show me what you mean by groups with a few screenshots so I can see how I might tackle it?

**Comment by Gemini04126** [comment]
![image](https://github.com/user-attachments/assets/7a84ca19-700e-4633-8b53-71f285193400)
Over on the sidebar when you select a node, there's this area.

**Comment by daleblackwood** [comment]
Added to branch 1.4, currently testing

**Comment by daleblackwood** [comment]
Thanks for the find, now in release v1.4, available in releases, awaiting asset approval from Godot
