### ISSUE TITLE
Minor gaps in wall using WallMeshSegmentShaper

### ISSUE THREAD

**Issue by GGAlanSmithee** [daleblackwood/goshapes#50]
@daleblackwood first of all, thank you so very much for the latest update 🙇🏼 what an amazing improvement in terms of performance and devx/UX - the `WallMeshSegmentShaper` scales well beyond my needs.

I understand, as you have previously pointed out, that you are maintaining this addon with a limited amount of time, so feel free to ignore any and all of my issues, but I am posting here to provide feedback in an open forum without expectations of any action on your part.

Using the `WallMeshSegmentShaper`, there seems to be some minor gaps at various places. I will continue to look into this on my end, but are there any known tricks to making the `WallMeshSegmentShaper` behave well in terms of what model to use, etc?

See screenshots for result and context:

![image](https://github.com/user-attachments/assets/8485ae27-81ed-48d1-8711-bdce25cc7d61)
![image](https://github.com/user-attachments/assets/320f3e4c-ba32-4027-919c-0cde9e563112)
![image](https://github.com/user-attachments/assets/94cff90d-957a-47f4-b83e-4015321b981d)

**Comment by daleblackwood** [comment]
Great idea - I'll add an overlap value into 1.4, to make it customizable. Auto-gap detection is a little bit problematic with mesh caching.

**Comment by daleblackwood** [comment]
I've added an overlapping parameter in v1.4.

**Comment by GGAlanSmithee** [comment]
That sounds like a super reasonable solution - thanks! Will give it a try later today.
