### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by lucasthomaz97** [daleblackwood/goshapes#6]
![SampleIsland tscn - Experiences - Godot Engine 06_05_2023 21_11_33](https://user-images.githubusercontent.com/60408080/236651358-6ff17367-0fbe-4f64-b118-6723badf8fcc.png)
![SampleIsland tscn - Experiences - Godot Engine 06_05_2023 21_13_06](https://user-images.githubusercontent.com/60408080/236651375-f0c75f07-1fd5-4480-896f-c8ab24b6c9f3.png)

just running any sample file, it shows the error message in the prints
i tried to solve this bugs for myself, but nothing i did made it worked.
i also didn't understood how to build the meshes, but congratulations for the plugin idea, it's exactly what i always wanted in godot!

**Comment by Crittecol** [comment]
Same error on run for me, additionally samples open ok but moving the points throws

E 0:00:09:0145   parse_message: Condition "p_args.size() < 10" is true. Returning: ERR_INVALID_DATA
  <C++ Source>   scene/debugger/scene_debugger.cpp:174 @ parse_message()

and

E 0:00:09:0145   debug: Condition "_try_capture(command, data, captured) != OK" is true. Continuing.
  <C++ Source>   core/debugger/remote_debugger.cpp:475 @ debug()

**Comment by daleblackwood** [comment]
Thanks for bringing this to my attention, I'm due to take a look soon. Could either of you let me know which version of Godot you experienced the issue in?

**Comment by lucasthomaz97** [comment]
> Thanks for bringing this to my attention, I'm due to take a look soon. Could either of you let me know which version of Godot you experienced the issue in?

Mine was 4.0.2, the latest stable in that time

**Comment by daleblackwood** [comment]
Hi, I've merged in some fixes and updated the Godot asset library link, I'm awaiting approval. In the mean time, if you need to get through the problem now, I'd recommend cloning the project from Github manually and copying the asset in.
