### ISSUE TITLE
Shapes lose connection to Material resource

### ISSUE THREAD

**Issue by lewiji** [daleblackwood/goshapes#7]
Hi, nice plugin! Enjoying it so far.

I've noticed that if I create a Material for the MeshShapers of my shapes, and save that Material to the filesystem, after some time the material in the MeshShaper gets made unique and loses its connection to the saved material. This is a bit of a pain as it's nice to be able to have a central place in the filesystem to tweak and improve reused materials, and the unique materials add extra draw calls I think, too.

Cheers.

**Comment by daleblackwood** [comment]
Thanks for the heads up. If you do submit a fix, I'm happy to do a PR and some testing, otherwise I won't be updating for a few months.
