### ISSUE TITLE
Making Mesh Walls missing from the readme

### ISSUE THREAD

**Issue by FLamparski** [daleblackwood/goshapes#8]
I noticed that the section "Making Mesh Walls", referenced in the readme, is actually missing, and it seems like the the most important section. Would it be possible to document this process? Thanks!

**Comment by daleblackwood** [comment]
That's a great idea. I won't be able to add it for a month or two, but I can give some pointers right now.

In your 3D software, start from origin (0,0,0) and create a mesh that spans the X axis. This is the mesh that will be wrapped around the shape. Make sure to add plenty of subdivisions to make it easier to wrap.

Take a look at the included cliff.obj mesh for clues.

**Comment by daleblackwood** [comment]
Updated readme and added sample scenes, referencing them in the readme.
