### ISSUE TITLE
Make it possible to place mesh objects instances instead of PackedScenes?

### ISSUE THREAD

**Issue by kordian-kowalski** [daleblackwood/goshapes#9]
I have a ton of assets that come as .obj files which work very well in the engine itself, but as they are imported as Mesh objects rather than PackedScenes these cannot be used directly with this plugin. 

I suppose a new Shaper implementation could be created that does this?

**Comment by daleblackwood** [comment]
This will be possible from 1.3, feel free to test it out on: https://github.com/daleblackwood/goshapes/tree/feature/threading
